### ISSUE TITLE
Copy events do not trigger local state changes in latest version of Chrome.

### ISSUE THREAD

**Issue by bertho-zero** [CharlesStover/use-clippy#13]
If I copy anything on the page with `CTRL + C` or via the context menu the value then `useClippy` is not updated, maybe missing a listener like `window.addEventListener('copy', func)`

**Comment by bertho-zero** [comment]
This event is never called in the latest version of chrome.

```
navigator.clipboard.addEventListener('copy', clipboardListener)
```

**Comment by wootwoot1234** [comment]
@CharlesStover  Can you publish version 1.0.5 to npm?

**Comment by CharlesStover** [comment]
Thanks for pointing this out. TravisCI deprecated their old deployment configuration. I've just updated it, and 1.0.5 should be headed out now!

**Comment by wootwoot1234** [comment]
Thanks!
