### ISSUE TITLE
Get clipboard contents on load?

### ISSUE THREAD

**Issue by wootwoot1234** [CharlesStover/use-clippy#15]
I'm able to get the clipboard contents when I copy something on the page but not when I already have something in the clipboard.

Is it possible to get the clipboard contents on page load?

**Comment by CharlesStover** [comment]
[This should be supported.](https://github.com/CharlesStover/use-clippy/blob/master/src/use-clippy.ts#L185) I assume you are using `1.0.5`?

**Comment by wootwoot1234** [comment]
Here's my code.  Am I doing something wrong?

    const Header = props => {
        const [clipboard, setClipboard] = useClippy();

        useEffect(() => {
            console.log("clipboard", clipboard);
        }, [clipboard]);

        return (
            {clipboard}
        );
    };

**Comment by CharlesStover** [comment]
Your code looks like valid React code. What is the current behavior, and what do you expect to happen?

**Comment by wootwoot1234** [comment]
I expect it to render the contents of the clipboard on load. Right now, it
only renders the contents of the clipboard if you copy something from the
page into the clipboard.

**Comment by CharlesStover** [comment]
I am unable to reproduce this. Do you experience this issue in [the demo](https://charlesstover.github.io/use-clippy/)?
