### ISSUE TITLE
Reading the clipboard does not work in some versions of Safari.

### ISSUE THREAD

**Issue by stfenjobs** [CharlesStover/use-clippy#18]
hi

i used safari open the demo https://charlesstover.github.io/use-clippy/

it can't read my clipboard , but chrome can do

**Comment by CharlesStover** [comment]
I've heard mixed feedback on Safari support. More information, such as the specific Safari version, may be necessary to assist in debugging.

As a Windows developer, I am unable to test this hook in Safari, but I do welcome PRs to address this.

**Comment by arthur31416** [comment]
Hi there,
If I understand correctly, there was no support for the clipboard API on Safari.
Which is now supported:
https://webkit.org/blog/10855/
When I tested, it worked well so I think you can safely close this issue.
