### ISSUE TITLE
paste not updating `clipboard`

### ISSUE THREAD

**Issue by donavon** [CharlesStover/use-clippy#19]
I can read the current content of the `clipboard` just fine, but if I paste new content, `clipboard` is not updated. I tried it on https://charlesstover.github.io/use-clippy/ as well, but nothing.

Am I missing something or does this hook not support live paste events?

Edit: I tried this on macOS with both Chrome and Brave.

And yes, I allowed clipboard access.
![image](https://user-images.githubusercontent.com/887639/83944780-24c4bd00-a7d4-11ea-9672-732ebedfaedd.png)

**Comment by CharlesStover** [comment]
I don't understand what you mean by paste events. Pasting does not change the contents of the clipboard, so nothing should be occurring on paste. What is the expected behavior?

**Comment by donavon** [comment]
I guess I misunderstood exactly what this package was supposed to do. 

I found this [article](https://web.dev/image-support-for-async-clipboard/#images) that explains how to capture pasted images, which is what I was trying to accomplish.
