### ISSUE TITLE
React version dependency 

### ISSUE THREAD

**Issue by vanchoy** [CharlesStover/use-clippy#54]
Could you please update the dependency for the React version, because on `npm i` it looks for React 16.8 and we are already on 18+ and it throws an error. On React 17+ works with manual `--force` install.

**Comment by CharlesStover** [comment]
I can take a look at this. Are you saying React 17 can be made to work, but React 18 can't? I'm curious if this means it requires a refactor to get it to work.

**Comment by vanchoy** [comment]
It looks specifically for React 16.8 if I'm not wrong. On React 17+, 18+ works with `--force` install.
